DROP TABLE TICKET;
DROP TABLE BOOKER;
CREATE TABLE TICKET 
(
  VISIT_DATE DATE NOT NULL 
, TICKET_TYPE NVARCHAR2(10) NOT NULL 
, ADULT NUMBER 
, NAME NVARCHAR2(20) NOT NULL 
, TEEN NUMBER 
, KID NUMBER 

); 

CREATE TABLE BOOKER 
(
NAME NVARCHAR2(20) NOT NULL 
, EMAIL VARCHAR2(30 BYTE) 
, TEL VARCHAR2(20) NOT NULL 

);

-- 사용자함수만들기
CREATE OR REPLACE FUNCTION dateCheck(d date)
RETURN varchar
IS
  c varchar(10);
BEGIN
  IF       TO_DATE(sysdate,'YYYY-MM-DD')<TO_DATE(d,'YYYY-MM-DD')     THEN  c := 'yes';
  ELSIF    TO_DATE(sysdate,'YYYY-MM-DD')>=TO_DATE(d,'YYYY-MM-DD')    THEN  c := 'no';
  END IF;
RETURN c;
END;

-- query = "SELECT grade(10000) FROM DUAL";